[tool.poetry]
name = "danarbu"
version = "0.1.0"
description = ""
authors = ["Johann Fridriksson <jof@jof.guru>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
